### ISSUE TITLE
Hardly-readable fragments in documentation tooltips

### ISSUE THREAD

**Issue by dkjb634** [JetBrains/EnhancedUnrealEngineDocumentation#13]
Having EnhancedUnrealEngineDocumentation plugin installed corrupt documentation tooltips: it contains unreadable/hardly-readable text.

Examples: UE_LOG, GENERATED_BODY, TickComponent

<img width="498" alt="image" src="https://github.com/JetBrains/EnhancedUnrealEngineDocumentation/assets/87329202/1c9a2261-5f56-4260-b068-1448f2158f9a">
<img width="351" alt="image" src="https://github.com/JetBrains/EnhancedUnrealEngineDocumentation/assets/87329202/28d4535e-c445-4ddf-aff9-725d99706733">
<img width="781" alt="image" src="https://github.com/JetBrains/EnhancedUnrealEngineDocumentation/assets/87329202/55961161-5e01-465c-a6eb-eb6d29d631b7">

Reproduced on 
MacOS
2023.2.2/2023.3 EAP 3. 
UE 5.3
Rider Night

**Comment by Artanisx** [comment]
I confirm this issue is also present in
2023.2.2
UE 5.2.1

and on Windows 10 22H2 19045.3570.

**Comment by DecoyRS** [comment]
Fixed in the 1.231.1 version of the plugin, check Plugins > Installed > Update
