### ISSUE TITLE
Rider 2022.3 Support

### ISSUE THREAD

**Issue by mystal** [JetBrains/EnhancedUnrealEngineDocumentation#4]
Rider 2022.3 was released recently, but this plugin is marked as incompatible.

![image](https://user-images.githubusercontent.com/109628787/207674795-a9f40043-08cd-41a5-b241-7429a3974222.png)

It would be great to update the plugin for the new version. I'm happy to help doing this work, but would need some mentoring. I see where the supported build number is set, but I'm sure there's more to it than just bumping that.
```gradle
pluginSinceBuild = 223.7000
pluginUntilBuild = 223.*
```

**Comment by DecoyRS** [comment]
Hello @mystal
Sorry for ghosting this issue for so long, but I've finally got my hands to fix the plugin for 2023.1.
Why no 2022.3? You were right, bumping the plugin version compatibility wasn't enough - Rider's SDK was borked and I had to push internal fixes.

**Comment by mystal** [comment]
Thanks for the update! Looks like it's working on the latest EAP.
