### ISSUE TITLE
Howering over any meta specifier doesn't show improved documentation

### ISSUE THREAD

**Issue by dkjb634** [JetBrains/EnhancedUnrealEngineDocumentation#9]
STR:
         UPROPERTY(meta=(ConfigHierarchyEditable, AllowedTypes="qwe", HideInDetailPanel, AllowedTypes="abs"))
	AActor foo;

Hover over any meta specifier. Rider behaves as default.

**Comment by DecoyRS** [comment]
Fixed in v1.0.12, will be available for Rider 2023.3
